//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.19 at 12:53:55 AM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ktelabs.ru/soap/ws", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.ktelabs.soap.ws;
